# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20170831_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 7, 3, 20, 163011, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
