# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20170831_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 7, 6, 52, 463227, tzinfo=utc)),
        ),
    ]
